// <auto-generated />
using System;
using Infrastucture;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace webAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250228232543_UpdateModulo2")]
    partial class UpdateModulo2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Classroom")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("Id_Modulo")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("Domain.Models.CursoProfessor", b =>
                {
                    b.Property<Guid>("Id_Curso")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id_Professor")
                        .HasColumnType("char(36)");

                    b.HasKey("Id_Curso", "Id_Professor");

                    b.HasIndex("Id_Professor");

                    b.ToTable("CursoProfessores");
                });

            modelBuilder.Entity("Domain.Models.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("Id_Curso")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id_Professor")
                        .HasColumnType("char(36)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("WorkLoad")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Curso");

                    b.HasIndex("Id_Professor");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("Domain.Models.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiniResume")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("webAPI.Domain.Models.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CoordenadorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Curriculum")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MonthlyPrice")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PedagogicalCoordination")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Proposal")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RegistrationPrice")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StartForecast")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TotalPrice")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Workload")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CoordenadorId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Domain.Models.Aula", b =>
                {
                    b.HasOne("Domain.Models.Modulo", "Modulo")
                        .WithMany("Aulas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Domain.Models.CursoProfessor", b =>
                {
                    b.HasOne("webAPI.Domain.Models.Curso", "Curso")
                        .WithMany("CursoProfessores")
                        .HasForeignKey("Id_Curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Professor", "Professor")
                        .WithMany("CursoProfessores")
                        .HasForeignKey("Id_Professor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Domain.Models.Modulo", b =>
                {
                    b.HasOne("webAPI.Domain.Models.Curso", "Curso")
                        .WithMany("Modulos")
                        .HasForeignKey("Id_Curso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Professor", "Professor")
                        .WithMany("Modulos")
                        .HasForeignKey("Id_Professor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("webAPI.Domain.Models.Curso", b =>
                {
                    b.HasOne("Domain.Models.Professor", "Coordenador")
                        .WithMany("CursosCoordenados")
                        .HasForeignKey("CoordenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordenador");
                });

            modelBuilder.Entity("Domain.Models.Modulo", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("Domain.Models.Professor", b =>
                {
                    b.Navigation("CursoProfessores");

                    b.Navigation("CursosCoordenados");

                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("webAPI.Domain.Models.Curso", b =>
                {
                    b.Navigation("CursoProfessores");

                    b.Navigation("Modulos");
                });
#pragma warning restore 612, 618
        }
    }
}
