// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Application.Interfaces;
using Infrastucture;


#nullable disable

namespace webAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("webAPI.Domain.Models.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Curriculum")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MonthlyPrice")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PedagogicalCoordination")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Proposal")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RegistrationPrice")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StartForecast")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TotalPrice")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Workload")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
